version: '3.3'

services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0.30
    restart: always
    env_file:
    - ./config/db.env
    networks:
      - srv_glpi
    volumes:     
      - mysql_data:/var/lib/mysql
    ports:
      - 3306
  nginx:
    container_name: glpi
    depends_on: 
      - mysql
    image: nginx:stable-alpine
    privileged: true
    restart: unless-stopped
    volumes:
    - ./glpi:/usr/share/nginx/glpi
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./glpi/files/:/var/lib/glpi/files
    hostname: glpi
    networks:
      - srv_glpi        
    ports:
      - "8087:80"
  phpfpm:
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php
    depends_on: 
    - nginx   
    hostname: php
    networks:
      - srv_glpi   
    restart: always   
    privileged: true
    volumes:
    - ./glpi:/usr/share/nginx/glpi:rw
  
volumes:
  mysql_data:

networks:
  srv_glpi:
    driver: bridge