---
- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: true
    when: ansible_distribution == "Ubuntu"

- name: Copy webserver conf file
  template:
    src: glpi.conf.j2
    dest: "{{ webserver_path }}"
    when: ansible_distribution == "Ubuntu"

- name: Create a symbolic link webserver conf
  file:
    src: "{{ webserver_path }}"
    dest: "{{ webserver_symlinks }}"
    owner: root
    group: root
    state: link
    when: ansible_distribution == "Ubuntu"

- name: Start and Enable Apache
  service:
    name: apache2
    enabled: yes
    state: started
    when: ansible_distribution == "Ubuntu"