---
- name: Process to install Apache (Ubuntu)
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: Copy webserver conf file
      template:
        src: glpi.conf.j2
        dest: "{{ webserver_path }}/glpi.conf"

    - name: Create a symbolic link webserver conf
      ansible.builtin.file:
        src: "{{ webserver_path }}/glpi.conf"
        dest: "{{ webserver_symlinks }}/glpi.conf"
        owner: root
        group: root
        state: link

    - name: Start and Enable Apache
      service:
        name: apache2
        enabled: yes
        state: started
      notify:
        - Restart Apache
