---
- name: Extract and download glpi
  ansible.builtin.unarchive:
    src: "{{ glpi_url }}"
    dest: "{{ glpi_path }}"
    remote_src: yes

- name: Permission glpi {{ glpi_path }}/glpi
  ansible.builtin.file:
    path: "{{ glpi_path}}/glpi"
    state: directory
    recurse: true
    owner: "{{ glpi_owner }}"
    group: "{{ glpi_group }}"
    mode: '0775'

- name: Create a symbolic link glpi-console
  ansible.builtin.file:
    src: "{{ glpi_path }}/glpi/bin/console"
    dest: "{{ glpi_console_symlinks }}"
    owner: root
    group: root
    state: link 

# - name: Install Automatic GLPI
#   command: "glpi-console glpi:database:install -Lpt_BR -H {{ ansible_hostname }} -d {{ db_glpi }} -u {{ db_user_name }} -p {{ db_glpi_passwd }} --no-telemetry --force -n"