---
# tasks file for glpi
- name: Include task list webserver
  include_tasks: "{{ webserver }}.yml"

- name: Include task list php
  include_tasks: php.yml

- name: Include task list glpi
  include_tasks: glpi.yml
