---
# tasks file for glpi
- name: Include task list webserver
  ansible.builtin.include_tasks: 
    file: "{{ webserver }}.yml"

- name: Include task list php
  ansible.builtin.include_tasks: 
    file: php.yml

- name: Include task list glpi
  ansible.builtin.include_tasks: 
    file: glpi.yml

- name: Include task list Xdebug
  ansible.builtin.include_tasks:
    file: xdebug.yml