---
- name: Process to install Php (Ubuntu)
  when: ansible_distribution == "Ubuntu"
  block:

  - name: Install Prerequistes (Ubuntu)
    ansible.builtin.apt:
      name: "{{req_pack_ubuntu}}"
      state: present
    
  - name: Add repository PHP (Ubuntu)
    ansible.builtin.apt_repository: 
      repo: 'ppa:ondrej/php'
      state: present

  - name: Install PHP package (Ubuntu)
    ansible.builtin.apt:
      name: "{{ pack_v8_0 }}"
      update_cache: yes
      state: present