---
# vars file for mariadb
sql_daemon: mysql
percona_server8_0: percona-server-server
percona_server5_7: 
  - percona-server-server-5.7
  - percona-server-common-5.7 
percona_socket: /var/run/mysqld/mysqld.sock
percona_release_8: ps80
percona_release_5: ps57
percona_version: 5.7

db_port: 3306

phyton_version: 3.8


# Packages
# Install GnuPG, the GNU Privacy Guard
# Install dependencies Phyton3 + Phyton Dependencies Ansible + Mysql
packages:
  - gnupg2 
  - curl
  - libmysqlclient-dev
  - python-dev
  - python-pip
  - python-mysqldb
  - python{{ phyton_version }}
  - python3-dev
  - python3-pip
  - python3-pymysql
  - python3-mysqldb
