version: '3.3'
services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0.30
    restart: always
    env_file:
    - ./config/db.env
    networks:
      - srv_glpi
    volumes:     
      - mysql_data:/var/lib/mysql
    ports:
      - 3306
  glpi:
    container_name: glpi
    depends_on: 
      - mysql
    image: almalinux:minimal
    privileged: true
    tty: true
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/glpi/:/usr/share/glpi
    hostname: glpi
    environment:
      - TIMEZONE=America/Fortaleza
    networks:
      - srv_glpi        
    ports:
      - "8087:80"
    
volumes:
  mysql_data:

networks:
  srv_glpi:
    driver: bridge