---
# vars file for glpi
webserver: apache
webserver_path: /etc/apache2/sites-available
webserver_symlinks: /etc/apache2/sites-enabled
php_version: "8.0"
req_pack_ubuntu:
  - lsb-release
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - wget
  - zip
pack_v8_0:
  - php8.0-cli
  - php8.0-imap
  - php8.0-ldap
  - php8.0-xmlrpc
  - php8.0-soap
  - php8.0-curl
  - php8.0-snmp
  - php8.0-zip
  - php8.0-apcu
  - php8.0-gd
  - php8.0-mbstring
  - php8.0-mysql
  - php8.0-xml
  - php8.0-bz2
  - php8.0-intl
