version: '3.3'

services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0.30
    restart: always
    env_file:
    - ./files/mysql/db.env
    networks:
      - srv_glpi
    volumes:     
      - mysql_data:/var/lib/mysql
    ports:
      - 3306
  apache:
    container_name: glpi
    depends_on: 
      - mysql
    build:
      context: .
      dockerfile: ./apache-phpalpine/Dockerfile
    privileged: true
    restart: unless-stopped
    volumes:
    - ./glpi:/var/www/html/glpi
    - ./glpi/config:/var/glpi/config
    - ./files/etc/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
    hostname: glpi
    networks:
      - srv_glpi        
    ports:
      - "8087:80"
volumes:
  mysql_data:

networks:
  srv_glpi:
    driver: bridge