pipeline {
    agent any
    stages {
        stage('Collect Variables') {
            steps {
                echo "Version Choice is: ${GLPI_VERSION}"
                echo "Branch or Tag Choice is: ${BRANCH_TAG}"
                echo "SO Versions is: ${SO_VERSION}"               
            }
        }
        stage('Prepare Environment') {
            steps {
                script {
                    if (env.GLPI_VERSION == 'latest') {
                    sh '''
                        TAG_URL=$(curl -s https://api.github.com/repos/glpi-project/glpi/releases/latest \
                        | grep browser_download_url \
                        | cut -d '"' -f 4)
                        curl -s -L --create-dirs -o /usr/share/glpi "$TAG_URL"
                        '''                   
                    } else {
                        echo 'Another Version'
                    }
                }
            }
        }
    }
}
