pipeline {
    agent any
    stages {
        stage('Collect Variables') {
            steps {
                echo 'Version Choice is:' ${GLPI_VERSION}
                echo 'Branch or Tag Choice is:' ${BRANCH_TAG}
                echo 'SO Versions is:' ${SO_VERSION}
            }
        }
    }
}
